#!/usr/bin/env bash

# clean slate
rm -rf ~/cs193lab4

wget -P ~ https://github.com/Purdue-CSUSB/CS-193-F2017/blob/master/Labs/Lab4/cs193lab4.tgz?raw=true
tar -xzf ~/cs193lab4.tgz -C ~
rm -rf ~/cs193lab4.tgz

# say its done
echo -e '\ndirectory ~/cs193lab4 reset!'
